"""
This type stub file was generated by pyright.
"""

from mongoengine.queryset.base import BaseQuerySet

class QuerySet(BaseQuerySet):
    def __iter__(self):
        ...
    
    def __len__(self):
        ...
    
    def count(self, with_limit_and_skip: bool = ...):
        ...
    
    def no_cache(self):
        ...
    


class QuerySetNoCache(BaseQuerySet):
    def cache(self):
        ...
    
    def __iter__(self):
        ...
    


class QuerySetNoDeRef(QuerySet):
    ...


