"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def query(_doc_cls: Incomplete | None = ..., **kwargs):
    ...

def update(_doc_cls: Incomplete | None = ..., **update):
    ...

