"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from mongoengine.errors import InvalidQueryError

class QNodeVisitor:
    def visit_combination(self, combination):
        ...
    
    def visit_query(self, query):
        ...
    


class DuplicateQueryConditionsError(InvalidQueryError):
    ...


class SimplificationVisitor(QNodeVisitor):
    def visit_combination(self, combination):
        ...
    


class QueryCompilerVisitor(QNodeVisitor):
    document: Incomplete
    def __init__(self, document) -> None:
        ...
    
    def visit_combination(self, combination):
        ...
    
    def visit_query(self, query):
        ...
    


class QNode:
    AND: int
    OR: int
    def to_query(self, document):
        ...
    
    def accept(self, visitor) -> None:
        ...
    
    @property
    def empty(self):
        ...
    
    def __or__(self, other):
        ...
    
    def __and__(self, other):
        ...
    


class QCombination(QNode):
    operation: Incomplete
    children: Incomplete
    def __init__(self, operation, children) -> None:
        ...
    
    def accept(self, visitor):
        ...
    
    @property
    def empty(self):
        ...
    


class Q(QNode):
    query: Incomplete
    def __init__(self, **query) -> None:
        ...
    
    def accept(self, visitor):
        ...
    
    @property
    def empty(self):
        ...
    


