"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

DEFAULT_CONNECTION_NAME: str
class MongoEngineConnectionError(Exception):
    ...


def register_connection(alias, db: Incomplete | None = ..., name: Incomplete | None = ..., host: Incomplete | None = ..., port: Incomplete | None = ..., read_preference=..., username: Incomplete | None = ..., password: Incomplete | None = ..., authentication_source: Incomplete | None = ..., authentication_mechanism: Incomplete | None = ..., **kwargs) -> None:
    ...

def connect(db: Incomplete | None = ..., alias=..., **kwargs):
    ...

