"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

class DeReference:
    max_depth: Incomplete
    reference_map: Incomplete
    object_map: Incomplete
    def __call__(self, items, max_depth: int = ..., instance: Incomplete | None = ..., name: Incomplete | None = ...):
        ...
    


