from _typeshed import Incomplete

class NotRegistered(Exception): ...
class InvalidDocumentError(Exception): ...
class LookUpError(AttributeError): ...
class DoesNotExist(Exception): ...
class MultipleObjectsReturned(Exception): ...
class InvalidQueryError(Exception): ...
class OperationError(Exception): ...
class NotUniqueError(OperationError): ...
class SaveConditionError(OperationError): ...
class FieldDoesNotExist(Exception): ...

class ValidationError(AssertionError):
    errors: Incomplete
    field_name: Incomplete
    message: Incomplete
    def __init__(self, message: str = ..., **kwargs) -> None: ...
    def __getattribute__(self, name): ...
    def to_dict(self): ...
