"""
This type stub file was generated by pyright.
"""

"""
Helper functions, constants, and types to aid with MongoDB version support
"""
MONGODB_34 = ...
MONGODB_36 = ...
def get_mongodb_version(): # -> tuple[Any, ...]:
    """Return the version of the default connected mongoDB (first 2 digits)

    :return: tuple(int, int)
    """
    ...

